.changeset/odd-windows-work.md, packages/nextjs/app/blockexplorer/transaction/_components/TransactionComp.tsx, templates/base/package.json, templates/base/packages/nextjs/app/blockexplorer/address/[address]/page.tsx.template.mjs, templates/base/packages/nextjs/app/blockexplorer/transaction/[txHash]/page.tsx, templates/base/packages/nextjs/utils/scaffold-eth/common.ts
What I had to do:
1. Sync branch `upstream-main` branch with SE-2 (in the GitHub UI... but you can also add the remote locally and do it locally)
2. Pull `upstream-main` locally
3. Create `backmerge-upstream` branch from the `main` branch
4. Merge `upstream-main` => `backmerge-upstream`
5. Fix conflicts
- This will be particular for every case, maybe we should document it (if it's not already). In this case I had to "accept yours" in the root package.json file and add the `next:serve` manually into the template/base package.json.
6 Run `yarn add changeset` to create the changeset file (selectect "patch")
7. Create PR. Since this is a fork, it automatically points to the SE-2 repo, so I have to manually change it (not sure if there is a way to default to this repo, even if it's a fork). …
=> Backmerge upstream

.changeset/curvy-drinks-wave.md, templates/base/packages/nextjs/components/scaffold-eth/Balance.tsx, templates/base/packages/nextjs/components/scaffold-eth/FaucetButton.tsx, templates/base/packages/nextjs/hooks/scaffold-eth/useWatchBalance.ts, templates/base/packages/nextjs/package.json
For some wired reason, when if we use `~` for `burner-connector` it give me "module not found error"
, using `^` does seem to solve that problem
=> use caret for burner-connector versioning

CONTRIBUTING.md, README.md
Initial tweaks to adapt old SE-2 Readme and Contributing guide to new create-eth repo.
Maybe I deleted too much stuff in Readme for a initial iteration, we can get back basic SE-2 screenshot and features from initial part of the Readme if you prefer 🙌
Fixes #10
=> Adapt readme and contributing guide to create-eth repo

.husky/pre-commit, .lintstagedrc.json, .prettierignore, .prettierrc.json, contributors/RFC-extensions.md, eslint.config.js, package.json, src/config.ts, src/declarations/merge-pacakges.d.ts, src/main.ts, src/tasks/copy-template-files.ts, src/tasks/create-first-git-commit.ts, src/types.ts, src/utils/extensions-tree.ts, src/utils/external-extensions.ts, src/utils/find-files-recursively.ts, src/utils/link.ts, src/utils/merge-package-json.ts, src/utils/parse-arguments-into-options.ts, src/utils/prompt-for-missing-options.ts, src/utils/render-outro-message.ts, yarn.lock
- Configured prettier inline with SE-2 repo config
- Formatted files with prettier
- Configured [ESlint v9](https://eslint.org/docs/latest/use/getting-started) and [typescript-eslint](https://typescript-eslint.io/getting-started/)
- Both prettier and eslint ignores templates dir
- Fixed eslint issues
- Configured pre-commit hooks with husky and lint-staged
Tried keeping typescript-eslint rules inline with SE-2. 
1. Install dependencies : 
```
yarn install
```
2. Add `const x = 5` in `src/cli.ts` and try running : 
```
git add . && git commit -m "this should fail"
```
This will run pre-commit and hopefully it should fail (since x is unused variable) 
cc @Pabl0cks, could you please test this on windows also once, because I remmember in SE-2 while configuring husky it was not working …
=> Configure eslint and prettiier

.changeset/shaggy-eagles-chew.md, templates/base/.github/workflows/lint.yaml.template.mjs, templates/extensions/foundry/.github/workflows/lint.yaml.args.mjs, templates/extensions/foundry/packages/foundry/.gitignore.template.mjs, templates/extensions/foundry/packages/foundry/deployments/.gitignore, templates/extensions/hardhat/.github/workflows/lint.yaml.args.mjs
1. Templatised lint.yaml depending on solidity frameWork option chosen
2. In foundry gitignore only ignore deployments of `31337.json`  and unignore rest all chains. 
- If we don't do above, when we have deployed contract on other chain (it will be present in broadcast dir) but not in `deployments` dir which causes the action to fail checkout this [example](https://github.com/technophile-04/subgraph-foundry/actions/runs/9240550369/job/25420965111)
- After unignoring  other chains it started passing checkout example [here](https://github.com/technophile-04/subgraph-foundry/actions/runs/9240733250/job/25421362566)
=> fix foundry gh-actions

.github/workflows/lint.yml, src/cli.ts
Created a lint workflow similar to SE-2 repo which runs wherever a PR is created against main and after merging / pushing things to main. 
Here is failed example, where I commited with `--no-verify` flag an un formatted code https://github.com/scaffold-eth/create-eth/actions/runs/9272915257/job/25511808068
Fixes #22
=> configure lint gh-action

templates/extensions/foundry/packages/foundry/deployments/31337.json, templates/extensions/foundry/packages/foundry/script/Deploy.s.sol.template.mjs
This will allow people to create extension's which adds new contract and also deployments for them. 
Switch to this branch then: 
1. Start cli : 
```
yarn dev
```
2. Scaffold new app, with eip-5792 extension: 
```
yarn cli -e technophile-04/eip-5792:foundry
```
3. Choose foundry as extension too
Here is extension [repo](https://github.com/technophile-04/eip-5792/tree/foundry/extension/packages)
--- 
Adding contracts and deployments in hardhat does not require any templatisation since we can create separate `01_deploy_..` file and main deploy script `99_deploy...` will consider all the deployments. 
But in foundry this is not the case [checkout this](https://github.com/scaffold-eth/scaffold-eth-2/pull/781#issuecomment-2018642266) for more details
=> templatised foundry deploy script

.changeset/config.json, .changeset/eleven-ways-count.md, package.json, src/main.ts, yarn.lock
fixes https://github.com/scaffold-eth/create-eth/issues/41
In issue I wrote that message is not spamming in default mac terminal, but currently it also spams a message when add `-e` option.
Changing [listr](https://www.npmjs.com/package/listr) to [listr2](https://www.npmjs.com/package/listr2) fixes the issue. I didn't find a way to fix it without changing the lib since looks like everything should work as expected
Tested with and without `-e` , subgraph and eip-712 extension and everything works great, installing is ok and no spamming message
Deployment to vercel also works
Also I changed `baseBranch` in changeset config since there is no `cli` branch currently and changeset fails with error
`🦋  error Error: Failed to find where HEAD diverged from cli. Does cli exist?`
=> Fix spamming message

.husky/pre-commit, .lintstagedrc.json, lefthook.yml, package.json, yarn.lock
Migrated to [lefhook](https://github.com/evilmartians/lefthook) from husky due #49. 
The main selling point of lefthook for us: 
1. It doesn't require `postinstall` to work
2. since its a single machine code binary also remove the need to mind external dependencies like (Husky + [lint-staged](https://github.com/okonet/lint-staged) , they both add roughly around fifften hundred dependencies to node_modules <- it was mentioned [here](https://arc.net/l/quote/rriulboi)
Fixes #48 
<details>
<summary>
</summary>
Git Hooks lets you fire some custom scripts when certain actions happens like (commit, push, etc). All you need is good knowledge of Bash scripts and internals of git. You can configure it in `./.git/hooks/pre-commit` . 
But while working on project you are interested in that project’s …
=> migrate to lefthook from husky

src/tasks/prettier-format.ts
Noticed this while testing #68, actually I we forgot to remove extra console.log in #55
=> remove console log from runPrettier function

contributors/TEMPLATING.md
For me it wasn't clear how versions in merged `package.json` files are defined. From readme, I thought that always version from second `package.json` is taken. So I updated readme to make it clear for other devs. 
Source https://github.com/zppack/merge-packages/blob/master/src/index.js#L104
If you want to test examples, you can add this to your first `templates/base/packages/nextjs/package.json` deps
```
"a": "~1.2.3",
"b": "^1.0.0",
```
and create new `package.json` at `templates/solidity-frameworks/hardhat/packages/nextjs/package.json
```
{
"dependencies": {
"a": "^1.0.0",
"b": ">=1.2.0 <1.3.0"
}
}
```
run 
```
yarn cli -s hardhat --skip test-packages-merge
```
and check resulting nextjs package
=> feat: update merge packages info

package.json, src/main.ts, src/types.ts, src/utils/parse-arguments-into-options.ts, src/utils/prompt-for-missing-options.ts, yarn.lock
- Removed prompt for installing dependencies
- `--skip-install` is an escape hatch (not completely sure if we should remove or keep it but sometimes its pretty handy)
- Removed prettiers plugins which were installed due to #55 + moved prettier to devDependency
=> don't prompt for install + remove prettier plugins

contributors/THIRD-PARTY-EXTENSION.md
Tried writing very basic doc for creating third party extension with phase 1 & 2. Lol I think it could way better / improved.
=> third party extension doc(v0.1)

.changeset/spotty-rocks-notice.md, src/tasks/copy-template-files.ts, src/utils/link.ts, src/utils/parse-arguments-into-options.ts
Sorry @carletex I didn't notice you self-assigned the issue. 😨 
`-> Only foundry or hardhat folders should be copied / merged if selected.` - this is fixed
Regarding
`-> Ideally "none" option should not be present (or disabled). Maybe a config file in the 3rd party extension?`
Since we show prompts before reading extension, it will require to change flow.
I think we have two simpler options
1. In README of extension add explicit flag `--solidity-framework` and show both options (for me this option is better)
---
```
npx create-eth@latest -e erc-20 --solidity-framework hardhat
```
OR
```
npx create-eth@latest -e erc-20 --solidity-framework foundry
```
---
2. Add flag meaning that solidity framework is required, so options will be without "none"
```
npx create-eth@latest -e erc-20 …
```
=> fix: soidity frameworks folders

.changeset/great-weeks-enjoy.md, src/cli.ts, src/types.ts, src/utils/external-extensions.ts, src/utils/parse-arguments-into-options.ts, src/utils/prompt-for-missing-options.ts
There are major 3 scenarios: 
1. The external extension don't have any solidity  framework dir 
Example: 
```shell
yarn cli ../test-eip -e eip-712
```
In this case we show all three options to user on TUI (hardhat, foundry, none)
2. The external extension contains only one solidity framework. 
Example: 
```shell
yarn cli ../test-eip -e technophile-04/eip-5792
```
The [above extension](https://github.com/technophile-04/eip-5792/tree/main/extension/packages) only has `hardhat` so we don't give user any option on TUI and select for them. 
Here there is small catch, what if in above extension user forcefully mention `foundry` using `-s` flag? 
In this PR, preference is given to external extension directory and `-s` flag is ignored
3. The external extension contains both solidity framework …
=> display solidity framework options based on extension

.changeset/tasty-ties-bow.md, templates/base/packages/nextjs/app/debug/_components/contract/Tuple.tsx, templates/base/packages/nextjs/app/debug/_components/contract/TupleArray.tsx, templates/base/packages/nextjs/app/debug/_components/contract/utilsContract.tsx, templates/base/packages/nextjs/components/scaffold-eth/Input/AddressInput.tsx, templates/base/packages/nextjs/components/scaffold-eth/ProgressBar.tsx, templates/base/packages/nextjs/hooks/scaffold-eth/useScaffoldEventHistory.ts, templates/base/packages/nextjs/hooks/scaffold-eth/useTransactor.tsx, templates/base/packages/nextjs/utils/scaffold-eth/contract.ts, templates/solidity-frameworks/hardhat/packages/hardhat/tsconfig.json
- revert #875 (https://github.com/scaffold-eth/scaffold-eth-2/pull/905)
- Fix typos (https://github.com/scaffold-eth/scaffold-eth-2/pull/906)
- Exclude external links from triggering progress bar ([#909](https://github.com/scaffold-eth/scaffold-eth-2/pull/909))
- Handle tx revert in `useTransactor` (https://github.com/scaffold-eth/scaffold-eth-2/pull/907)
- show blockexplorer link when transaction is reverted (https://github.com/scaffold-eth/scaffold-eth-2/pull/910)
- fix: useScaffoldEventHistory caching (https://github.com/scaffold-eth/scaffold-eth-2/pull/916)
- allow json module imports (https://github.com/scaffold-eth/scaffold-eth-2/pull/921)
I think we should also include : https://github.com/scaffold-eth/scaffold-eth-2/pull/921
=> backmerge 12 8 30

.changeset/odd-bananas-know.md, templates/base/packages/nextjs/tailwind.config.js.template.mjs, templates/solidity-frameworks/hardhat/packages/hardhat/hardhat.config.ts.template.mjs
- templatise tailwind light and dark theme
- this allow people to give SE-2 colors of their choice
- allow importing more stuff in hardhat.config.ts
- Since hardhat requires something to be present in `hardhat.config.ts` for example [plugins](https://hardhat.org/hardhat-runner/plugins#community-plugins)
- another example is exposing [tasks](https://hardhat.org/hardhat-runner/docs/advanced/create-task) 
1. use latest cli changes
```shell
yarn dev
```
2. Create a test instance: 
```shell
yarn cli ../test-my-new-extension -e technophile-04/tailwind-hardhat-tasks-extension
```
I have created [technophile-04/tailwind-hardhat-tasks-extension ](https://github.com/technophile-04/tailwind-hardhat-tasks-extension/) this extension which uses hardhat tasks and updates tailwind theme. 
3. Go to …
=> cli: templatise tailwind and hardhat config

.changeset/shiny-papayas-hide.md, templates/base/packages/nextjs/tailwind.config.js.template.mjs, templates/solidity-frameworks/hardhat/packages/hardhat/hardhat.config.ts.template.mjs
Since we already have those files (hardhat & tailwind config) on a template, I wonder if we should add some handy stuff.
- Solidity version
- Networks
- Tailwind extend theme
You can test with https://github.com/carletex/create-eth-extensions/tree/tailwind-extend-solidity-version
```
yarn cli -e carletex/create-eth-extensions:tailwind-extend-solidity-version
```
What do you think?
(I'll add the changeset if we like this)
=> Add template support for solidityVersion, networks and tailwind extend

.changeset/honest-dingos-serve.md, templates/base/README.md.template.mjs
Adds possibility to skip default Quick start block of README when creating extensions
Changed a bit newlines so it wont generate 2-3 empty lines depending on different options (well, sometimes it could be empty lines depending on extra lines of parameters or/plus for example when there's no `extraContent`; but it's still better than it was before, at least with `skipQuickStart: true` since it adds new line because default quick start block becomes `""`)
See reason and how to test [here](https://github.com/scaffold-eth/create-eth-extensions/pull/29#issuecomment-2433484793)
=> skipQuickStart param for README template

.changeset/friendly-boats-fix.md, src/tasks/copy-template-files.ts, templates/solidity-frameworks/foundry/packages/foundry/test/YourContract.t.sol
Earlier it was processing the exampleSolidityContract path always causing the extensions to break like `erc-20` when foundry was chosen. 
```shell
npx create-eth@latest -e erc-20 -s foundry
``` 
^ This breaks. 
Switch to this branch and then: 
```shell
yarn dev
```
```shell
yarn cli -e erc-20 -s foundry
```
=> process example solidity template only when required

.github/workflows/lint.yml, lefthook.yml, package.json, src/extensions.json, src/types.ts, src/utils/parse-arguments-into-options.ts, src/utils/system-validation.ts, tsconfig.json, yarn.lock
Updated pre-commit hook so that it does:
- Type check: By doing this we make sure that type error don't get into our code.
- eslint / typescript-eslint doesn't do typescheck [ref](https://github.com/typescript-eslint/typescript-eslint/issues/1037) and that's why [this happened](https://github.com/scaffold-eth/create-eth/pull/155#pullrequestreview-2450343240)
- lint check: we were already doing this.
- format: This is helpful for json files, by default eslint does not format json files, but prettier is able to do it nicely. This way we make sure people don't commit unformatted json files especially `extensions.json` file
Update gh-action `lint.yml` file to do typecheck too
---
Also updated the eslint related packages because on the main branch in `eslint.config.js` I was getting this:
And …
=> up eslint packages + type check and format in pre-commit

.changeset/real-rockets-rule.md, README.md, templates/base/packages/nextjs/app/blockexplorer/_components/PaginationButton.tsx, templates/base/packages/nextjs/app/blockexplorer/_components/SearchBar.tsx, templates/base/packages/nextjs/app/blockexplorer/_components/TransactionHash.tsx, templates/base/packages/nextjs/app/blockexplorer/page.tsx, templates/base/packages/nextjs/app/debug/_components/contract/DisplayVariable.tsx, templates/base/packages/nextjs/app/debug/_components/contract/TxReceipt.tsx, templates/base/packages/nextjs/app/debug/_components/contract/utilsDisplay.tsx, templates/base/packages/nextjs/components/scaffold-eth/Address/Address.tsx, templates/base/packages/nextjs/components/scaffold-eth/Address/AddressCopyIcon.tsx, templates/base/packages/nextjs/components/scaffold-eth/Balance.tsx, templates/base/packages/nextjs/components/scaffold-eth/Input/Bytes32Input.tsx, templates/base/packages/nextjs/components/scaffold-eth/Input/BytesInput.tsx, templates/base/packages/nextjs/components/scaffold-eth/Input/EtherInput.tsx, templates/base/packages/nextjs/components/scaffold-eth/Input/InputBase.tsx, templates/base/packages/nextjs/components/scaffold-eth/Input/IntegerInput.tsx, templates/base/packages/nextjs/utils/scaffold-eth/decodeTxData.ts, templates/base/packages/nextjs/utils/scaffold-eth/networks.ts, templates/example-contracts/hardhat/packages/hardhat/contracts/YourContract.sol, templates/solidity-frameworks/hardhat/packages/hardhat/.prettierrc.json, templates/solidity-frameworks/hardhat/packages/hardhat/hardhat.config.ts.template.mjs, templates/solidity-frameworks/hardhat/packages/hardhat/package.json
- Add celo to networks (https://github.com/scaffold-eth/scaffold-eth-2/pull/980)
- fix: Input components in form tag (https://github.com/scaffold-eth/scaffold-eth-2/pull/992)
- fix: removed unecessary logs for decoding tx in block-explorer (https://github.com/scaffold-eth/scaffold-eth-2/pull/985)
- Remove hardcoded colors (https://github.com/scaffold-eth/scaffold-eth-2/pull/991)
- Fix typo in blockexplorer notification (https://github.com/scaffold-eth/scaffold-eth-2/pull/995)
- Prettier for solidity (https://github.com/scaffold-eth/scaffold-eth-2/pull/994)
> NOTE: We shouldn't squash and merge instead do a normal merge
=> backmerge 25-11-24

src/curated-extensions.ts, src/extensions.json
For CLI to work internally we don't need `branch` strict check. Also removed the strict check for descriptionl.
=> remove strict check for branch in curated json

.changeset/spotty-fans-occur.md, src/dev/create-extension.ts
Hey guys,
I was working on an extension, where I deleted the default `YourContract.sol` file, which resulted in an error when I tried to use `yarn create-extension {projectName}`.
**Steps to reproduce:**
1. yarn cli
2. Delete e.g. the YourContract.sol file
3. yarn create-extension {projectName}
After this fix it should work like this:
=> Add warning for deleted files to prevent errors during processing

.changeset/eighty-ducks-tease.md, templates/base/packages/nextjs/package.json, templates/base/packages/nextjs/scaffold.config.ts.template.mjs, templates/base/packages/nextjs/services/web3/wagmiConfig.tsx, templates/example-contracts/hardhat/packages/hardhat/deploy/00_deploy_your_contract.ts, templates/solidity-frameworks/foundry/packages/foundry/script/Deploy.s.sol.template.mjs, templates/solidity-frameworks/hardhat/package.json, templates/solidity-frameworks/hardhat/packages/hardhat/.env.example, templates/solidity-frameworks/hardhat/packages/hardhat/hardhat.config.ts.template.mjs, templates/solidity-frameworks/hardhat/packages/hardhat/package.json, templates/solidity-frameworks/hardhat/packages/hardhat/scripts/importAccount.ts, templates/solidity-frameworks/hardhat/packages/hardhat/scripts/listAccount.ts, templates/solidity-frameworks/hardhat/packages/hardhat/scripts/runHardhatDeployWithPK.ts
- reverse rpc fallback order (https://github.com/scaffold-eth/scaffold-eth-2/pull/1010)
- Encrypt deployer PK on .env file (when using hardhat) (https://github.com/scaffold-eth/scaffold-eth-2/pull/1008 )
=> backmerge latest

.changeset/tame-donuts-thank.md, src/tasks/copy-template-files.ts
If you have `package.json` files in both `hardhat` and `foundry` folders of your extension, installation breaks. PR fixes it.
Extension to test (just two empty `package.json` files in both folders). Try from `main` and from this PR branch.
```
yarn cli -e rin-st/test-merge-packages
```
extension repo: https://github.com/rin-st/test-merge-packages
Note: I changed regex from `${sf}$` to `${sf}`. Wondering how first even worked since it requires solidityFramework at the end of the path.
=> Fix merge package.json files

templates/solidity-frameworks/foundry/packages/foundry/Makefile.template.mjs, templates/solidity-frameworks/foundry/packages/foundry/scripts-js/generateTsAbis.js
To test checkout https://github.com/carletex/ctf-devcon/pull/151 🙌
=> templatise foundry Makefile and add `--via-ir` flag

.changeset/little-onions-hug.md, templates/solidity-frameworks/foundry/package.json
We actually removed `deploy:verify` command from foundry package.json but forgot to remove it from the root.
=> foundry: remove deploy:verify from base package.json

.changeset/chatty-mugs-allow.md, src/utils/prompt-for-missing-options.ts, src/utils/validate-name.ts
added `basename(resolve(...))` as [here](https://github.com/scaffold-eth/create-eth/blob/main/src/utils/prompt-for-missing-options.ts#L29) so validation works only for the last folder in path
fixes #207
=> Fix: name as path when initializing 

.changeset/ten-pears-explode.md, templates/base/packages/nextjs/components/Header.tsx.template.mjs, templates/base/packages/nextjs/hooks/scaffold-eth/useScaffoldEventHistory.ts, templates/base/packages/nextjs/hooks/scaffold-eth/useScaffoldWatchContractEvent.ts, templates/solidity-frameworks/hardhat/package.json, templates/solidity-frameworks/hardhat/packages/hardhat/package.json
- **fix typo in package.json scripts for lint** (https://github.com/scaffold-eth/scaffold-eth-2/pull/1041)
- **Add `hardhat:clean` command to root of monorepo (https://github.com/scaffold-eth/scaffold-eth-2/pull/1043)**
- **Only render FaucetButton on localhost (https://github.com/scaffold-eth/scaffold-eth-2/pull/1047)**
- **fix: remove indexed event params (https://github.com/scaffold-eth/scaffold-eth-2/pull/1048)**
=> backmerge 10-02-25

contributors/TEMPLATING.md
The initial draft for initial rules.
I think this should probably be merged after #175. 
After #175 we can update other config files to follow the same patterns like updating `tailwind.config`, `nextjs.config` etc.
=> initial draft for template args rules

.changeset/hip-deers-search.md, templates/base/packages/nextjs/components/ScaffoldEthAppWithProviders.tsx.template.mjs
Moves temaplte provider after wagmi provider so that we allow more customization example https://www.rainbowkit.com/docs/authentication#set-up-sign-in-with-ethereum-and-nextauth
Ohh actually subgrpah extension no more requires the provider it was removed in https://github.com/scaffold-eth/create-eth-extensions/pull/43
=> move template provider after wagmi

.changeset/cuddly-rabbits-complain.md, templates/base/package.json
I think we forgot to backmerge the husky version update.
In v9 they seem to remove the requirement for [that file being executable](https://github.com/typicode/husky/releases/tag/v9.0.1)
<details>
<summary>
migration guide: 
</summary>
</details>
Now if create an instance with branch it should work 🙌
1. switch to this branch. 
2. build the package
```ts
yarn build
```
3. run cli: 
```ts
yarn cli -s hardhat
```
you can add this `page.tsx` of created page instance and it should run the precommit hook 
```ts
let y = 1;
y = "shiv";
```
=> up husky version in base package.json

.changeset/rude-walls-lie.md, src/tasks/create-first-git-commit.ts
In latest foundry nightly version [they removed](https://github.com/foundry-rs/foundry/pull/9884) `--no-commit` flag. So if you were on latest foundry nigtly version you would get: 
<details>
<summary>
error
</summary>
</details>
This PR removes the `--no-commit` from forge install. Being compatible with foundry nigtly version and current stable version too (which as `--no-commit` flag)
There won't be any breaking effect of this. 
The only difference will be people using v1-stable or lower version will get this commits on instance scaffolded: 
People who are on nightly and in future when foundry releasees this stable people will get only 1 commit: 
Run : 
```
foundryup --install nightly
```
check by `forge --version` <= this should say v1-nigtly
And run `npx create-eth@latest -s foundry` …
=> remove `--no-commit` flag for foundry

.github/workflows/release.yml
Tired it at : 
So I have the Version packages PR already here : https://github.com/technophile-04/test-changeset-flow-package/pull/20 
Now after I merge changes with changes at : https://github.com/technophile-04/test-changeset-flow-package/pull/21 
If you look at github actions on main it skipped the release section (hence not failing the action and showing "x") : 
checkout [this](https://github.com/technophile-04/test-changeset-flow-package/actions/runs/13974845084/job/39125873643) 
Fixes #204
=> skip relase action version packages

.github/workflows/release.yml
https://github.com/scaffold-eth/create-eth/actions/runs/14362000375/job/40265632601 
here it skipped because we already had #210 open, now the action do strict check for the title  so that it won't skip
=> do strict equal insted of contains

.changeset/cold-rings-sing.md, package.json
Actually we had in devDependency but since we want this to be ran while creating instance moved it to main dependency
=> (beta) fix fastify/deepMerge not found

.changeset/dry-readers-fry.md, templates/base/packages/nextjs/package.json
for some reason we still have `"@typescript-eslint/eslint-plugin": "~5.40.0",` package which was removed from se-2 long time ago.
https://github.com/scaffold-eth/scaffold-eth-2/pull/963/files#diff-e5237f683dda3354b835c7c7c94b9759db2c743d4ba94d47d7f8b8e0b2bfb442L42
And now it started to break linting. Removed this package and everything seems to work.
Also, current version of that package is included in `eslint-config-next`
Looks like they broke `^5.4.2` part
Fixes https://github.com/scaffold-eth/scaffold-eth-2/issues/1085
=> fix: remove outdated dep

.changeset/nervous-cheetahs-deny.md, contributors/TEMPLATING.md, templates/base/packages/nextjs/app/layout.tsx.template.mjs, templates/base/packages/nextjs/app/page.tsx.template.mjs, templates/base/packages/nextjs/components/Header.tsx.template.mjs, templates/base/packages/nextjs/components/ScaffoldEthAppWithProviders.tsx.template.mjs, templates/base/packages/nextjs/contracts/externalContracts.ts.template.mjs, templates/base/packages/nextjs/styles/globals.css.template.mjs, templates/base/packages/nextjs/utils/scaffold-eth/getMetadata.ts.template.mjs, templates/example-contracts/foundry/packages/foundry/script/Deploy.s.sol.args.mjs, templates/solidity-frameworks/foundry/packages/foundry/script/Deploy.s.sol.template.mjs, templates/utils.js
Update the `template.mjs` files to folllow rules which we mentioned in : 
https://github.com/scaffold-eth/create-eth/blob/beta/contributors/TEMPLATING.md#rules-for-template-args
Mainly it consist renaming of `${somethingImports}` => `${preConfigContent}` so the user know's that this arg variable is not just only for adding imports but also they can add new variables / logic their too along with imports
To test: 
```shell
yarn build:dev && yarn cli -e https://github.com/scaffold-eth/create-eth-extensions/tree/example-beta-extra-templates
```
--- 
In other PR I will update `ScaffoldEthProvider` more customizable and also `Header.tsx` so that people can replace Rainbowkit with some custom wallet etc(like dynamic or etc extensions). I think we will need to use …
=> (beta) more upate to template files

package.json, src/cli.ts, src/utils/system-validation.ts, yarn.lock
Requirements check when using npx
- node >= 20.18.3 (see https://github.com/scaffold-eth/scaffold-eth-2/pull/1052)
- yarn >= 1.0.0 with the note that >= 2.0.0 is recommended
- git >= 2.20.0, see below why. Could be changed if needed
<details><summary>Cursor git version suggest</summary>
<p>
```
Git 2.20.0 was released in 2018 and includes many modern features
This version is widely available on all platforms
Most modern Git features and security improvements are available from this version
```
</p>
</details> 
Fixes #162
=> Requirements check when doing npx

.changeset/lucky-pens-joke.md, templates/base/packages/nextjs/package.json, templates/base/packages/nextjs/styles/globals.css.template.mjs
- up wagmi, viem and rainbow-me/rainbwkit (https://github.com/scaffold-eth/scaffold-eth-2/pull/1108)
Ohh we have https://github.com/scaffold-eth/scaffold-eth-2/pull/1103 in this PR probably because last backmerge we didn't merge it as normal merge and instead did squash and merge. 
I checked the code and we already have the changes from that PR 🙌 
> NOTE: We should do a normal merge commit instead of squash and merge
```
yarn build:dev && yarn cli -e https://github.com/scaffold-eth/create-eth-extensions/tree/update-example-globall-css
```
=> backemerge 13-05-25

.changeset/modern-rabbits-knock.md, src/utils/external-extensions.ts
Request for fetching the available solidity framework was failing when using the default branch (`branch` was empty)
This PR fixes it using blob/HEAD.
=> GitHub: Fetch solidity framework folder correctly for default branch

src/dev/migrate-to-beta.ts
When migrating with the script extension, we're getting logs of the files in the order which is not depend on errors/warnings. So how it works now: 
1. I use script. I see the logs, I **scroll** for errors
2. I fix argument(s) in some file
3. I use script to recheck if I did it right, and errors disappear.
4. I **scroll** for a new error. Go to 1
---
This PR changes the order of the files in the logs:
1. Files with no issues
2. Files with only new args warnings (which are not always needed)
3. Files with errors which 100% needed to be fixed.
<details><summary>Logs example</summary>
<p>
```
yarn migrate-to-beta externalExtensions/se-2-challenges
Analyzing extension: externalExtensions/se-2-challenges/extension
Comparing with beta version: …
```
=> Migration script: files priority

.changeset/shiny-eagles-greet.md, src/extensions.json
This adds the `challenge-stablecoins` shortcut to the extensions.json
When this has been merged and included in a release of create-eth we will need to update the install instructions in the README here https://github.com/scaffold-eth/se-2-challenges/pull/295/ to reflect the correct version and shortcut.
=> Add stablecoins challenge

src/extensions.json
As part of:
- https://github.com/BuidlGuidl/SpeedRunEthereum-v2/issues/229
- https://github.com/scaffold-eth/se-2-challenges/pull/323 (to 329)
- https://github.com/austintgriffith/speedrun-grader/pull/24
We should merge this when all the above is merged and release a new version + update challenges README. We can do it in steps if we want.
We want to remove the numbers from the curated extensions (challenges)
=> extension list: numbered challenges => not numbered challenges
