scaffold-eth/create-eth

.changeset/mighty-tools-impress.md
contributors/DEVELOPER-GUIDE.md

We are testing publishing to NPM

Change contributing md

---

.changeset/perfect-owls-trade.md
.changeset/small-rats-switch.md
templates/base/packages/nextjs/components/scaffold-eth/Faucet.tsx
templates/base/packages/nextjs/components/scaffold-eth/FaucetButton.tsx
templates/base/packages/nextjs/hooks/scaffold-eth/useTransactor.tsx
templates/base/packages/nextjs/package.json

- update useTransactor parameter types (scaffold-eth#846)

Backmerge main upstream

---

.changeset/red-beans-press.md
.changeset/sweet-stingrays-wonder.md
templates/base/packages/nextjs/hooks/scaffold-eth/useDeployedContractInfo.ts
templates/base/packages/nextjs/package.json
templates/base/packages/nextjs/utils/scaffold-eth/getMetadata.ts
templates/base/packages/nextjs/utils/scaffold-eth/getParsedError.ts

- Bump wagmi, viem and rainbowkit versions (scaffold-eth#849)
- Add default favicon (scaffold-eth#851)
NOTE: We shouldn't squash and merge this, instead do a normal merge

Weekly cli backmerge

---

.changeset/cool-feet-fetch.md
package.json
yarn.lock

checkout:  https://github.com/typicode/husky/issues/884
It was mentioned in docs after you click yarn [here](https://typicode.github.io/husky/how-to.html#manual-setup)  :

fix: add and configure pinst

---

LICENCE.txt

Adding MIT Licence to the repo, same file as SE-2 but with 2024 date.

Add LICENCE

---

templates/extensions/foundry/packages/foundry/script/VerifyAll.s.sol

replace `data` field with `input` to match [alloy-rs](https://github.com/alloy-rs/alloy/tree/main/crates/consensus/src/transaction) transaction type.

fix : update verify script

---

.changeset/grumpy-carpets-compare.md
src/curated-extensions.ts

https://github.com/scaffold-eth/create-eth-extensions/pull/12 was merged.

Add ponder as curated extension

---

.changeset/young-moose-move.md
src/utils/external-extensions.ts
src/utils/parse-arguments-into-options.ts

allow any case extension name in dev mode

---

.changeset/neat-points-cheer.md
src/curated-extensions.ts

https://github.com/scaffold-eth/create-eth-extensions/pull/25

add eip-5792 to curated list of extension

---

.changeset/five-students-clap.md
templates/base/packages/nextjs/app/debug/_components/DebugContracts.tsx

- fix: localStorage -> sessionStorage in debug contracts page (https://github.com/scaffold-eth/scaffold-eth-2/pull/975)

Weekly backmerge

---

src/extensions.json

Add ERC-721 extension to curated extensions.

Add ERC-721 extension

---

.changeset/cool-vans-kick.md
templates/solidity-frameworks/foundry/packages/foundry/Makefile
templates/solidity-frameworks/foundry/packages/foundry/package.json
templates/solidity-frameworks/foundry/packages/foundry/scripts-js/parseArgs.js

Merge changes from this commit https://github.com/scaffold-eth/scaffold-eth-2/commit/d196ae272ab26247b92dad18aaffa6549027bacd 
except remove this line:
`let verify = false;` , line 15, file parseArgs.js  because it is unused
The error happens because the path to parseArgs is `scripts/parseArgs.js` whereas it should be `scripts-js/parseArgs.js`

Add changes from foundry-se-2

---

.changeset/cyan-clouds-smile.md
templates/base/packages/nextjs/package.json

- up burner-connector version (https://github.com/scaffold-eth/scaffold-eth-2/pull/1021)

backmerge 26/12/24

---

.changeset/tall-fans-tap.md
src/utils/link.ts

Hey guys,
This is the continuation of https://github.com/scaffold-eth/create-eth/pull/171/.
Cheers,
Tamas

Do not copy/link .DS_Store files - macOS only

---

.changeset/rude-bugs-shout.md
src/extensions.json

I'm using the final branch name, without the **--extension**. 
To be able to test it, you have to wait until we change the branch names or add **--extension** at the **branch** element on the json.

Add SRE challenges extensions to curated list

---

.changeset/great-days-lick.md
templates/base/packages/nextjs/app/debug/_components/DebugContracts.tsx
templates/base/packages/nextjs/package.json

- update contract sort order in numberic way (https://github.com/scaffold-eth/scaffold-eth-2/pull/1032)
- downgrade wagmi and viem version (https://github.com/scaffold-eth/scaffold-eth-2/pull/1038)

backmerge 24-01-25

---

templates/base/packages/nextjs/tailwind.config.js.template.mjs

Example extension with updated tw config: (just noticed that I named extension branch wrong)
```
yarn cli -s hardhat -e https://github.com/scaffold-eth/create-eth-extensions/tree/beta-update-scaffold-config
```
Extension PR: https://github.com/scaffold-eth/create-eth-extensions/pull/58

Update tailwind config template

---

.changeset/olive-carrots-learn.md
templates/base/packages/nextjs/package.json
templates/base/packages/nextjs/styles/globals.css.template.mjs

- fix dark mode variant (https://github.com/scaffold-eth/scaffold-eth-2/pull/1096)
- Up viem, wagmi and rainbowkit (fixes indexDB warning)(https://github.com/scaffold-eth/scaffold-eth-2/pull/1099) 
> NOTE: We should do a normal merge commit

backmerge 21-4-25

---

.changeset/new-hounds-joke.md
templates/base/packages/nextjs/app/blockexplorer/_components/AddressComponent.tsx
templates/base/packages/nextjs/app/blockexplorer/_components/ContractTabs.tsx
templates/base/packages/nextjs/app/blockexplorer/address/[address]/page.tsx.template.mjs

- remove hardcode string and use AddressType (https://github.com/scaffold-eth/scaffold-eth-2/pull/1103)
> NOTE: We should we do a normal merge instead of squash and merge

backmerge 30-05-25

---

templates/base/.github/workflows/lint.yaml.template.mjs
templates/base/packages/nextjs/app/layout.tsx.template.mjs
templates/base/packages/nextjs/components/Header.tsx.template.mjs
templates/base/packages/nextjs/public/manifest.json.template.mjs
templates/utils.js

Adds typecheck for passed arguments. Fixed default args which had wrong types
tested with extension https://github.com/scaffold-eth/create-eth-extensions/tree/beta-extra-examples 
```
yarn cli -e https://github.com/scaffold-eth/create-eth-extensions/tree/beta-extra-examples
```
Fixes #191

Typecheck for arguments

---

src/tasks/create-first-git-commit.ts

Show create-eth version on initial commit

---

.changeset/two-rockets-swim.md
templates/base/.cursor/rules/scaffold-eth.mdc.template.mjs
templates/base/packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton/AddressInfoDropdown.tsx
templates/base/packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton/RevealBurnerPKModal.tsx
templates/base/packages/nextjs/components/scaffold-eth/RainbowKitCustomConnectButton/index.tsx
templates/base/packages/nextjs/hooks/scaffold-eth/useScaffoldEventHistory.ts
templates/base/packages/nextjs/utils/scaffold-eth/contract.ts

- Use `deployedOnBlock` from deployedContracts in useScaffoldEventHistory (https://github.com/scaffold-eth/scaffold-eth-2/pull/1134)
- Reveal burner pk option (https://github.com/scaffold-eth/scaffold-eth-2/pull/1137)
- Add cursor rules example for `useScaffoldEventHistory` (https://github.com/scaffold-eth/scaffold-eth-2/pull/1141)

backmerge 24-07-25

---

.changeset/sour-dodos-like.md
templates/base/packages/nextjs/app/debug/_components/contract/WriteOnlyFunctionForm.tsx
templates/base/packages/nextjs/hooks/scaffold-eth/useScaffoldEventHistory.ts
templates/base/packages/nextjs/hooks/scaffold-eth/useScaffoldWriteContract.ts
templates/base/packages/nextjs/hooks/scaffold-eth/useTransactor.tsx
templates/base/packages/nextjs/utils/scaffold-eth/contract.ts
templates/solidity-frameworks/hardhat/packages/hardhat/scripts/generateTsAbis.ts

- fix: getting deployedOnBlock when no receipt (https://github.com/scaffold-eth/scaffold-eth-2/pull/1143)
- fix contract interactions error (https://github.com/scaffold-eth/scaffold-eth-2/pull/1146)
- fix `useScaffoldEventHistory` to properly calculate `nextBlock` (https://github.com/scaffold-eth/scaffold-eth-2/pull/1144)

backmerge 01-08-25

---

contributors/THIRD-PARTY-EXTENSION.md

To be the same as in docs.
See commit https://github.com/scaffold-eth/se-2-docs/pull/134/commits/0f8a1bb9fdada15ee73bac4cb5900a92eec6bba0

Microfix: articles

---

.changeset/modern-cobras-sing.md

https://github.com/scaffold-eth/create-eth/pull/343/files

changeset for challenge rename
